Repository hudoro-solusi-digital/neron, pull requests merged in 2021-08, with the labels that each got.

#33 [#32] v0.1.7 Candidate - Update component
  package.json
  src/components/atoms/Icon/Icons/IcDashboard.tsx
  src/components/atoms/Icon/Icons/IcHamburger.tsx
  src/components/atoms/Icon/Icons/IcHistory.tsx
  src/components/atoms/Icon/Icons/IcInfo.tsx
  src/components/atoms/Icon/Icons/IcLogin.tsx
  src/components/atoms/Icon/Icons/IcLogout.tsx
  src/components/atoms/Icon/Icons/IcNotification.tsx
  src/components/atoms/Icon/Icons/IcSearch.tsx
  src/components/atoms/Icon/Icons/IcSettings.tsx
  src/components/atoms/Icon/Icons/IcSwap.tsx
  src/components/atoms/Icon/Icons/IcTrash.tsx
  src/components/atoms/Icon/Icons/IcUser.tsx
  src/components/atoms/Icon/Icons/index.tsx
  src/components/atoms/Icon/index.tsx
  src/components/atoms/Input/styles.ts
  src/components/atoms/Text/index.tsx
  src/components/atoms/Text/styles.ts
  src/utils/interfaces.ts
  src/utils/types.ts
Labels: enhancement

#35 [#34] v0.1.8 Candidate - Add label value component
  package.json
  src/components/atoms/Grid/index.tsx
  src/components/atoms/Icon/Icons/IcArrowDown.tsx
  src/components/atoms/Icon/Icons/IcArrowLeft.tsx
  src/components/atoms/Icon/Icons/IcArrowRight.tsx
  src/components/atoms/Icon/Icons/IcArrowUp.tsx
  src/components/atoms/Icon/Icons/IcDollar.tsx
  src/components/atoms/Icon/Icons/IcSend.tsx
  src/components/atoms/Icon/Icons/IcWallet.tsx
  src/components/atoms/Icon/Icons/index.tsx
  src/components/atoms/Input/styles.ts
  src/components/atoms/LabelValue/index.tsx
  src/components/atoms/LabelValue/styles.ts
  src/components/atoms/index.ts
  src/stories/LabelValue/LabelValue.stories.tsx
  src/utils/interfaces.ts
Labels: enhancement

#36 Fix gap props in Grid
  package.json
  src/components/atoms/Grid/index.tsx
  src/components/atoms/LabelValue/styles.ts
  src/utils/styles.ts
Labels: bug

#40 [#39] - Improved LabelValue component
  src/components/atoms/LabelValue/index.tsx
  src/components/atoms/LabelValue/styles.ts
  src/utils/interfaces.ts
Labels: enhancement

#41 [#37] - Add Card component
  package.json
  src/components/atoms/Card/index.tsx
  src/components/atoms/index.ts
  src/stories/Card/Card.stories.tsx
  src/utils/interfaces.ts
Labels: enhancement

#42 [#6] - Added Instalation Guide and Components API
  CONTRIBUTING.md
  README.md
Labels: documentation

#44 [#43] - Add CONTRIBUTING.md
  .prettierrc.json
  CONTRIBUTING.md
  package.json
  src/utils/types.ts
Labels: documentation

#46 [#45] - Fix README.md info
  README.md
  package.json
Labels: documentation
